AllCops:
  TargetRubyVersion: 2.4

# I feel like it's fine for a single parameter.
Style/FormatStringToken:
  Enabled: false

Style/Documentation:
  Exclude:
    - 'test/**/*'

Metrics/ClassLength:
  Exclude:
    - 'test/**/*'

Metrics/AbcSize:
  Exclude:
    - 'test/**/*'
